import { CharacterFromSwapi } from 'src/characters/entities/character.entity';

export const mockedCharacters: CharacterFromSwapi[] = [
  {
    name: 'Luke Skywalker',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/people/1/',
    films: ['https://swapi.dev/api/people/1/'],
    species: ['https://swapi.dev/api/people/1/'],
    vehicles: ['https://swapi.dev/api/people/1/'],
    starships: ['https://swapi.dev/api/people/1/'],
    created: 'https://swapi.dev/api/people/1/',
    edited: 'https://swapi.dev/api/people/1/',
    url: 'https://swapi.dev/api/people/1/',
  },
  {
    name: 'Anakin Skywalker',
    height: '172',
    mass: '77',
    hair_color: 'blond',
    skin_color: 'fair',
    eye_color: 'blue',
    birth_year: '19BBY',
    gender: 'male',
    homeworld: 'https://swapi.dev/api/people/1/',
    films: ['https://swapi.dev/api/people/1/'],
    species: ['https://swapi.dev/api/people/1/'],
    vehicles: ['https://swapi.dev/api/people/1/'],
    starships: ['https://swapi.dev/api/people/1/'],
    created: 'https://swapi.dev/api/people/1/',
    edited: 'https://swapi.dev/api/people/1/',
    url: 'https://swapi.dev/api/people/2/',
  },
];
